// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

// Protobuf Java Version: 3.25.3
package me.hvkcoder.java_basic.io.netty.protobuf.proto;

public final class MessageDataProto {
  private MessageDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
     * @return The dataType.
     */
    me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType getDataType();

    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
     * @return Whether the person field is set.
     */
    boolean hasPerson();
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
     * @return The person.
     */
    me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person getPerson();
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
     */
    me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.PersonOrBuilder getPersonOrBuilder();

    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
     * @return Whether the student field is set.
     */
    boolean hasStudent();
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
     * @return The student.
     */
    me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student getStudent();
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
     */
    me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.StudentOrBuilder getStudentOrBuilder();

    me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData}
   */
  public static final class MessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData)
      MessageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageData() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.class, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.Builder.class);
    }

    /**
     * Protobuf enum {@code me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PersonType = 0;</code>
       */
      PersonType(0),
      /**
       * <code>StudentType = 1;</code>
       */
      StudentType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PersonType = 0;</code>
       */
      public static final int PersonType_VALUE = 0;
      /**
       * <code>StudentType = 1;</code>
       */
      public static final int StudentType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return PersonType;
          case 1: return StudentType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType)
    }

    private int dataBodyCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PERSON(2),
      STUDENT(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return PERSON;
          case 3: return STUDENT;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_ = 0;
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @java.lang.Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
     * @return The dataType.
     */
    @java.lang.Override public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType getDataType() {
      me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType result = me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType.forNumber(dataType_);
      return result == null ? me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType.UNRECOGNIZED : result;
    }

    public static final int PERSON_FIELD_NUMBER = 2;
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
     * @return Whether the person field is set.
     */
    @java.lang.Override
    public boolean hasPerson() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
     * @return The person.
     */
    @java.lang.Override
    public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person getPerson() {
      if (dataBodyCase_ == 2) {
         return (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) dataBody_;
      }
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance();
    }
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
     */
    @java.lang.Override
    public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.PersonOrBuilder getPersonOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) dataBody_;
      }
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance();
    }

    public static final int STUDENT_FIELD_NUMBER = 3;
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
     * @return Whether the student field is set.
     */
    @java.lang.Override
    public boolean hasStudent() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
     * @return The student.
     */
    @java.lang.Override
    public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student getStudent() {
      if (dataBodyCase_ == 3) {
         return (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) dataBody_;
      }
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance();
    }
    /**
     * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
     */
    @java.lang.Override
    public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.StudentOrBuilder getStudentOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) dataBody_;
      }
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType.PersonType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) dataBody_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType.PersonType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) dataBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData)) {
        return super.equals(obj);
      }
      me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData other = (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getPerson()
              .equals(other.getPerson())) return false;
          break;
        case 3:
          if (!getStudent()
              .equals(other.getStudent())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + PERSON_FIELD_NUMBER;
          hash = (53 * hash) + getPerson().hashCode();
          break;
        case 3:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData)
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.class, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.Builder.class);
      }

      // Construct using me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        dataType_ = 0;
        if (personBuilder_ != null) {
          personBuilder_.clear();
        }
        if (studentBuilder_ != null) {
          studentBuilder_.clear();
        }
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_descriptor;
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData getDefaultInstanceForType() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.getDefaultInstance();
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData build() {
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData buildPartial() {
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData result = new me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.dataType_ = dataType_;
        }
      }

      private void buildPartialOneofs(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData result) {
        result.dataBodyCase_ = dataBodyCase_;
        result.dataBody_ = this.dataBody_;
        if (dataBodyCase_ == 2 &&
            personBuilder_ != null) {
          result.dataBody_ = personBuilder_.build();
        }
        if (dataBodyCase_ == 3 &&
            studentBuilder_ != null) {
          result.dataBody_ = studentBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData) {
          return mergeFrom((me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData other) {
        if (other == me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case PERSON: {
            mergePerson(other.getPerson());
            break;
          }
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                dataType_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getPersonFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataBodyCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getStudentFieldBuilder().getBuilder(),
                    extensionRegistry);
                dataBodyCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dataType_ = 0;
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @java.lang.Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
       * @return The dataType.
       */
      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType getDataType() {
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType result = me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType.forNumber(dataType_);
        return result == null ? me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData.DataType data_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.Builder, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.PersonOrBuilder> personBuilder_;
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       * @return Whether the person field is set.
       */
      @java.lang.Override
      public boolean hasPerson() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       * @return The person.
       */
      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person getPerson() {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) dataBody_;
          }
          return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return personBuilder_.getMessage();
          }
          return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       */
      public Builder setPerson(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       */
      public Builder setPerson(
          me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       */
      public Builder mergePerson(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person value) {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance()) {
            dataBody_ = me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.newBuilder((me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            personBuilder_.mergeFrom(value);
          } else {
            personBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       */
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.Builder getPersonBuilder() {
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       */
      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.PersonOrBuilder getPersonOrBuilder() {
        if ((dataBodyCase_ == 2) && (personBuilder_ != null)) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) dataBody_;
          }
          return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance();
        }
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Person person = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.Builder, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance();
          }
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.Builder, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.PersonOrBuilder>(
                  (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();
        return personBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.Builder, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.StudentOrBuilder> studentBuilder_;
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       * @return Whether the student field is set.
       */
      @java.lang.Override
      public boolean hasStudent() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       * @return The student.
       */
      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student getStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) dataBody_;
          }
          return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return studentBuilder_.getMessage();
          }
          return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       */
      public Builder setStudent(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       */
      public Builder setStudent(
          me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       */
      public Builder mergeStudent(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student value) {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance()) {
            dataBody_ = me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.newBuilder((me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            studentBuilder_.mergeFrom(value);
          } else {
            studentBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       */
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       */
      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.StudentOrBuilder getStudentOrBuilder() {
        if ((dataBodyCase_ == 3) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) dataBody_;
          }
          return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance();
        }
      }
      /**
       * <code>.me.hvkcoder.java_basic.io.netty.protobuf.proto.Student student = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.Builder, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.Builder, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.StudentOrBuilder>(
                  (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();
        return studentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData)
    }

    // @@protoc_insertion_point(class_scope:me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageData)
    private static final me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData();
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageData>
        PARSER = new com.google.protobuf.AbstractParser<MessageData>() {
      @java.lang.Override
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.MessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.hvkcoder.java_basic.io.netty.protobuf.proto.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code me.hvkcoder.java_basic.io.netty.protobuf.proto.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.hvkcoder.java_basic.io.netty.protobuf.proto.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.class, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person)) {
        return super.equals(obj);
      }
      me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person other = (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.hvkcoder.java_basic.io.netty.protobuf.proto.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.hvkcoder.java_basic.io.netty.protobuf.proto.Person)
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.class, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.Builder.class);
      }

      // Construct using me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_descriptor;
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person getDefaultInstanceForType() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance();
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person build() {
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person buildPartial() {
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person result = new me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person) {
          return mergeFrom((me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person other) {
        if (other == me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.hvkcoder.java_basic.io.netty.protobuf.proto.Person)
    }

    // @@protoc_insertion_point(class_scope:me.hvkcoder.java_basic.io.netty.protobuf.proto.Person)
    private static final me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person();
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.hvkcoder.java_basic.io.netty.protobuf.proto.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code me.hvkcoder.java_basic.io.netty.protobuf.proto.Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.hvkcoder.java_basic.io.netty.protobuf.proto.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.class, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student)) {
        return super.equals(obj);
      }
      me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student other = (me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.hvkcoder.java_basic.io.netty.protobuf.proto.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.hvkcoder.java_basic.io.netty.protobuf.proto.Student)
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.class, me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.Builder.class);
      }

      // Construct using me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        address_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_descriptor;
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student getDefaultInstanceForType() {
        return me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance();
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student build() {
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student buildPartial() {
        me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student result = new me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.address_ = address_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student) {
          return mergeFrom((me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student other) {
        if (other == me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 3;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.hvkcoder.java_basic.io.netty.protobuf.proto.Student)
    }

    // @@protoc_insertion_point(class_scope:me.hvkcoder.java_basic.io.netty.protobuf.proto.Student)
    private static final me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student();
    }

    public static me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.hvkcoder.java_basic.io.netty.protobuf.proto.MessageDataProto.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022.me.hvkcoder.java_basic." +
      "io.netty.protobuf.proto\"\266\002\n\013MessageData\022" +
      "W\n\tdata_type\030\001 \001(\0162D.me.hvkcoder.java_ba" +
      "sic.io.netty.protobuf.proto.MessageData." +
      "DataType\022H\n\006person\030\002 \001(\01326.me.hvkcoder.j" +
      "ava_basic.io.netty.protobuf.proto.Person" +
      "H\000\022J\n\007student\030\003 \001(\01327.me.hvkcoder.java_b" +
      "asic.io.netty.protobuf.proto.StudentH\000\"+" +
      "\n\010DataType\022\016\n\nPersonType\020\000\022\017\n\013StudentTyp" +
      "e\020\001B\013\n\tdata_body\"\"\n\006Person\022\n\n\002id\030\001 \001(\005\022\014" +
      "\n\004name\030\002 \001(\t\"4\n\007Student\022\n\n\002id\030\001 \001(\005\022\014\n\004n" +
      "ame\030\002 \001(\t\022\017\n\007address\030\003 \001(\tBB\n.me.hvkcode" +
      "r.java_basic.io.netty.protobuf.protoB\020Me" +
      "ssageDataProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_MessageData_descriptor,
        new java.lang.String[] { "DataType", "Person", "Student", "DataBody", });
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Person_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_hvkcoder_java_basic_io_netty_protobuf_proto_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
